{% set name = "json-rpc" %}
{% set version = "1.13.0" %}
{% set hash_type = "md5" %}
{% set hash_val = "6bc55e9cb58ce9a07da9ac50df10b958" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - jsonrpc
    - jsonrpc.backend
    - jsonrpc.tests
    - jsonrpc.dispatcher

  requires:
    - mock
    - nose

about:
  home: https://github.com/pavlov99/json-rpc
  license: MIT
  license_file: LICENSE.txt
  summary: 'JSON-RPC transport realisation'

extra:
  recipe-maintainers:
    - dharhas
    - ccordoba12
