{%set name = "json-rpc" %}
{%set version = "1.11.0" %}
{%set hash_type = "md5" %}
{%set hash_val = "c6ec280ce0812df25df3ec9207f2efcd" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - jsonrpc
    - jsonrpc.backend
    - jsonrpc.tests

  requires:
    - mock
    - nose

about:
  home: https://github.com/pavlov99/json-rpc
  license: MIT License
  summary: 'JSON-RPC transport realisation'

extra:
  recipe-maintainers:
    - dharhas
