# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lV2998LrCwmss4AbgSN3Vy+MtAbeFTqB/fnmgKlWjcxByfWU55XT7FEoBgMauwPWjzRB3bhVRjHxj+ENy+qSJysn1/HxRSFnzUuqXYwUm6s+AhCeDEaf0RINldEdTudCWXyfBakf59WUI/4GukGNaxTkT7RtAIJjG+5vNk2djTPHzUDbQjqv2PDqO8uIXdqWYJdYLITuPO+jMGWIAV9RTfIjb2soZP5LY/phpMjt4RAW1X5sJiGJuXENjB7cjQkwB6bxMrRjA1pF38wrMFPQZXr6z/aietQ93puw9rl8ubenorC8iQu0OZsj2EXnbbL0910rQn+HHC8d8vU+rCAKzK0o22tjquB9OEs5Y8IYmxo6KACUq4KHcArsR2l+lZHat+d8vF1e1XMKX88VEoV45zHISevtd7foqXhwo6Pg0oYeR1yJWaj3mTa3lcv+2rwjIDrdW3wWb06SDgOZCW1wjcCaoOG0kPdtIfB7aZRRxwSyXiJLL5HqsJLNF2ocjJLvEsHb8P9/p764XEG/qOux4S3HQEoi/5cFylf15jThzmUfh5yrYyQqEs3yKC7+H8RRk3i5Bx2myxvYIFYb3O5bf1PR2fXpGS/5HHrHk/rjLYCCbkqU4H/TnCAvyOBHzBWHR8cMlBFBANsCt59Ccl/zpqFiMWLkiaCEada9Nkl1JWk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
